cloud:
  aws:
    region:
      static: US_EAST_1
      auto: false
    credentials:
      access-key: AKIASQVR6LKQRBWHSGBX 
      secret-key: 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
    end-point:
      uri: https://sqs.us-east-1.amazonaws.com/173245618849/SkillCertQueue
      
application:
  bucket:
    name: skillcertbucket


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB
      
